spring:
  thymeleaf:
    #关闭缓存
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: '0327'  #密码要加‘’
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #连接池名字
      pool-name: DataHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接最大时间 默认 600000十分钟
      idle-timeout: 180000
      #最大连接数，默认10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间 0表示永久存活，默认1800000 30分钟
      max-lifetime: 1800000
      #连接超时时间，默认30000 30秒
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  redis:
    host: 202.117.43.251
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        #最大连接时间
        max-active: 8
        #最大连接阻塞时间,默认-1
        max-wait: 10000ms
        #最大连接数
        max-idle: 200
        #最小连接数
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回的类型别名（默认是类名）
  type-aliases-package: com.hhf.seckilldemo.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.hhf.seckilldemo.mapper: debug